name: Deploy Hugo with PaperMod to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    concurrency:
      group: "pages"
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Критически важно для PaperMod
          fetch-depth: 0

      - name: Initialize submodules
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.3'  # Укажите актуальную версию
          extended: true

      - name: Build with Hugo
        run: |
          hugo --minify --gc --verbose
          echo "Build complete"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
